### ISSUE TITLE
PSU Conversion

### ISSUE THREAD

**Issue by pgierz** [esm-tools/pymorize#40]
We should add a general purpose PSU unit converter to avoid salinity not being a real "unit"

Currently, converting `psu -> 0.001`:
```log
pymorize.units:handle_unit_conversion:120 - Converting units: psu -> 0.001
```
Gives:
```log
ValueError: Cannot convert variables:
    incompatible units for variable 'so': Unit expression cannot have a scaling factor.
```

See more ideas [here](https://stackoverflow.com/questions/39153885/how-to-define-and-use-percentage-in-pint).

This needs to go in `src/pymorize/units.py` as a general case added to the unit registry.

**Comment by mandresm** [comment]
This is related to #55.

There we are saying that the user needs to specify `g/kg` and that the mappings for CMOR tables need to map `0.001` to `g/kg`, but we could always define a new unit for pint where `psu = g/kg` so that both the CMOR table mappings and the users can use `psu` instead of `g/kg`.

**Comment by siligam** [comment]
> This is related to #55.
> 
> There we are saying that the user needs to specify `g/kg` and that the mappings for CMOR tables need to map `0.001` to `g/kg`, but we could always define a new unit for pint where `psu = g/kg` so that both the CMOR table mappings and the users can use `psu` instead of `g/kg`.

CMOR tables are treated read-only and any changes in the tables, must happen upstream. With this version of tables, we are struck with `0.001` as units and the same units is written down in the output netcdf files.
