### ISSUE TITLE
Dimensionless and other strange unit conversion

### ISSUE THREAD

**Issue by mandresm** [esm-tools/pymorize#54]
## Problem

Some units in the CMOR tables are listed as `0.001` or `1`. At the same time, the model output also have similar units. These units typically correspond to dimensionless units for example for the salinity the unit in the CMOR tables is `0.001` which really means in pyhical terms `g/Kg` (dimensionless).

The problem is that if we want to achieve an automatic conversion of units we need to tell our tool what these `0.001` unit means physically (g/kg) (i.e. what is it's physical quantity), and that might vary from variable to variable.

### On the model side

Specify the "physical" unit in the `rule` of the input yaml file:

```yaml
- rule:
    unit: g/kg
```

### On the CMOR tables side

Yaml file that is part of Pymorize repo, co-develop with the power users

```yaml
sst:
    "0.001": g/kg
```

This mapping can then be use to make `pymorize` and `pint` "understand" what the CMOR table means by `0.001`

**TODOS**

- [ ]

**Comment by pgierz** [comment]
Recommendation to keep this easily configurable. In the main user-yaml, add a key/value for `dimensionless_mapping_table: <some/path/to/a/file>`, e.g. in [`examples/sample.yaml`](https://github.com/esm-tools/pymorize/blob/main/examples/sample.yaml)
```diff
general:
    .... metadata relevant for humans
pymorize:
  # parallel: True
  warn_on_no_rule: False
  use_flox: True
  cluster_mode: fixed
  fixed_jobs: 12
  # minimum_jobs: 8
  # maximum_jobs: 30
+ dimensionless_mapping_table: data/pymorize/dimensionless_mappings.yaml

```

**Comment by pgierz** [comment]
Work on implementation in #55
