### ISSUE TITLE
Inconsistencies in check_is_subperiod

### ISSUE THREAD

**Issue by pgierz** [esm-tools/pymorize#59]
In `_check_is_subperiod`, there are a few inconsistencies:

* [x] Only the first object in the `rules` list is checked. Instead of:

```python
try:
    rule = self.rules[0]
except IndexError:
   ...
```
one would need:
```python
for rule in self.rules:
   ...
```
* [x] The filecache is used to determine what the frequency inside the NetCDF file is. However, there should be a way for the user to specify what the frequency is (override behaviour) and it does not seem to work correctly if the files do not contain a time dimension.

**Comment by siligam** [comment]
you are right, i need to use for loop and check the first file in each rule for frequency. I will fix that.

Concerning the `filecache`, it the netcdf does not have time dimension (may be the dimension is called something else or is it a scalar value), will the frequency information will be set by the user on the `rule` (say `rule.frequency`). Assuming `rule.frequency` attribute exists, first attempt will be to get the `frequency` information from that attribute and when it not set, `frequency` from `filecache` is used.

**Comment by pgierz** [comment]
You could extend your filecache to have something like `time_dim_name` (default `time`), but we have had weird cases where some models just has `"T"`

**Comment by siligam** [comment]
how to handle user defined frequency in the case of "Multi-variable Rule"? In "Single-variable Rule" it is straight-forward as to expect user setting `rule.frequency` to a scalar value but in case of "Multi-variable Rule", will the user be setting it to a list? Will the user be aware of such a thing before hand to write it down in the rule?

**Comment by pgierz** [comment]
Good question. To make it easier, I would make this part of the inputs section of the rule, so the user can specify the frequency those netcdf files have. So something like:
```yaml
rules:
    - name: my rule
      inputs:
         - path: /some/path/to/folder
           pattern: regex_for_files
           frequency: "M" # Optional, otherwise inferred from the first matching file
```

**Comment by siligam** [comment]
I think it is possible to detect the name of the time dimension

```python
import xarray as xr, numpy as np

def detect_time_dimension(filename):
    ds = xr.open_dataset(filename)
    datetime_type = np.dtype("datetime64[ns]")
    for name, coord in ds.coords.items():
        if datetime_type == coord.dtype:
            return name
```
can you cross-check with one of these weird cases you mentioned having 'T' as the name for time dimension. If it works, I might include it the filecache to grab the appropriate time dimension.

**Comment by siligam** [comment]
pytest fail with FileNotFound error when the following line is triggered:

`first_filenames.append(input_collection.files[0])`
 
the following is the reason for the error:
configs/test_config.yaml:      - path: "./some/other/path"

can you please suggest a valid path here?

**Comment by pgierz** [comment]
#58 includes code to automatically download and use test data on the FESOM PI mesh. I'll extract the commits into a new PR and you can cherry-pick from #60
